In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('../data/raw/Teen_Mental_Health_Dataset.csv')

In [3]:
df.head()

,age,gender,daily_social_media_hours,platform_usage,sleep_hours,screen_time_before_sleep,academic_performance,physical_activity,social_interaction_level,stress_level,anxiety_level,addiction_level,depression_label
0,14,male,7.9,Instagram,7.4,2.9,3.01,1.5,low,2,2,1,0
1,19,female,1.9,TikTok,8.0,2.9,3.22,0.8,high,8,1,10,0
2,17,female,1.3,Instagram,7.6,0.5,3.92,0.0,high,2,4,2,0
3,15,male,7.4,TikTok,6.9,1.6,3.48,0.8,medium,1,7,9,0
4,15,female,4.7,Both,4.9,3.0,2.37,1.4,medium,3,5,2,0

In [7]:
df['usage_category'] = pd.cut(
    df['daily_social_media_hours'],
    bins=[0,2,5,10],
    labels=['Low','Medium','High']
)

df['sleep_category'] = pd.cut(
    df['sleep_hours'],
    bins=[0,5,7,10],
    labels=['Poor','Average','Good']
)

In [8]:
df

,age,gender,daily_social_media_hours,platform_usage,sleep_hours,screen_time_before_sleep,academic_performance,physical_activity,social_interaction_level,stress_level,anxiety_level,addiction_level,depression_label,usage_category,sleep_category
0,14,male,7.9,Instagram,7.4,2.9,3.01,1.5,low,2,2,1,0,High,Good
1,19,female,1.9,TikTok,8.0,2.9,3.22,0.8,high,8,1,10,0,Low,Good
2,17,female,1.3,Instagram,7.6,0.5,3.92,0.0,high,2,4,2,0,Low,Good
3,15,male,7.4,TikTok,6.9,1.6,3.48,0.8,medium,1,7,9,0,High,Average
4,15,female,4.7,Both,4.9,3.0,2.37,1.4,medium,3,5,2,0,Medium,Poor
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1195,18,female,6.8,Instagram,6.6,2.0,2.76,1.0,low,3,4,4,0,High,Average
1196,16,male,2.3,Both,8.0,1.9,2.12,0.4,high,7,4,4,0,Medium,Good
1197,14,female,1.7,Both,8.7,0.7,3.98,0.8,high,1,1,1,0,Low,Good
1198,15,male,3.9,Both,8.5,2.1,3.19,0.6,high,7,9,9,0,Medium,Good
1199,16,female,4.7,TikTok,6.5,1.0,2.91,0.9,medium,5,7,3,0,Medium,Average

In [9]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1200 entries, 0 to 1199
Data columns (total 15 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   age                       1200 non-null   int64
 1   gender                    1200 non-null   str
 2   daily_social_media_hours  1200 non-null   float64
 3   platform_usage            1200 non-null   str
 4   sleep_hours               1200 non-null   float64
 5   screen_time_before_sleep  1200 non-null   float64
 6   academic_performance      1200 non-null   float64
 7   physical_activity         1200 non-null   float64
 8   social_interaction_level  1200 non-null   str
 9   stress_level              1200 non-null   int64
 10  anxiety_level             1200 non-null   int64
 11  addiction_level           1200 non-null   int64
 12  depression_label          1200 non-null   int64
 13  usage_category            1200 non-null   category
 14  sleep_category            1200 non-null   category
dtypes: category(2), float64(5), int64(5), str(3)
memory usage: 143.0 KB

In [10]:
df.drop(['stress_level', 'anxiety_level'], axis=1, inplace=True)

In [11]:
df.sample(15)

,age,gender,daily_social_media_hours,platform_usage,sleep_hours,screen_time_before_sleep,academic_performance,physical_activity,social_interaction_level,addiction_level,depression_label,usage_category,sleep_category
460,18,male,5.3,Both,5.1,1.2,3.32,1.8,low,8,0,High,Average
622,16,female,3.8,TikTok,5.3,1.5,2.04,1.5,high,5,0,Medium,Average
895,16,male,1.8,Instagram,4.9,2.3,2.67,1.4,medium,6,0,Low,Poor
844,16,male,8.0,Instagram,8.1,2.5,2.70,1.7,medium,7,0,High,Good
756,14,male,7.6,Instagram,5.8,1.9,3.49,1.7,high,3,0,High,Average
385,15,male,7.0,Both,8.7,3.0,2.84,1.4,medium,2,0,High,Good
243,16,female,7.8,TikTok,4.7,2.1,2.48,2.0,low,1,0,High,Poor
582,17,female,2.9,Both,7.5,1.4,3.42,1.7,low,3,0,Medium,Good
199,17,female,1.7,Both,6.3,1.5,2.66,1.8,low,10,0,Low,Average
439,13,female,2.4,Instagram,5.5,0.6,3.56,1.6,medium,7,0,Medium,Average
603,16,male,6.9,Instagram,6.8,1.1,3.33,1.0,medium,4,0,High,Average
1020,18,female,2.3,Instagram,4.2,0.9,3.84,1.3,high,10,0,Medium,Poor
1153,15,female,7.4,TikTok,8.9,2.9,3.39,1.1,high,1,0,High,Good
1187,18,male,2.0,Instagram,8.9,0.8,2.96,0.5,medium,2,0,Low,Good
213,18,female,1.9,TikTok,5.8,1.7,3.52,0.2,low,1,0,Low,Average

In [12]:
df.to_csv('../data/processed/process_Teen_mental_health.csv', index=False)